
package Interfaces;

import static Interfaces.Horarios.cone;
import Modelo.Conector;
import java.awt.Dimension;
import java.awt.Image;
import javax.swing.ImageIcon;

public class CrearHorarios extends javax.swing.JFrame {
 
    static String idUser;
      static Conector cone;
   private Dimension dim;
    
    public CrearHorarios() {
        
        initComponents();
        
         cone= new Conector();
        setResizable(false);
        
        dim=super.getToolkit().getScreenSize();
        super.setSize(dim);
        
        ImageIcon logo1=new ImageIcon(getClass().getResource("/Imagenes/calendariocrear.png"));
        ImageIcon tamaño=new ImageIcon(logo1.getImage().getScaledInstance(crearHorario.getWidth(), crearHorario.getHeight(), Image.SCALE_DEFAULT));
        crearHorario.setIcon(tamaño);
        
        setTitle("Horarios");
        
        txtInicioFecha.setText("");
        txtFinFecha.setText("");
        txtInicioHorario.setText("");
        txtFinHorario.setText("");
        txtTipoCargo.setText("");
        txtInstructor.setText("");
        
        
        inputInicioFecha.setVisible(false);
        inputFinFecha.setVisible(false);
        inputInicioHora.setVisible(false);
        inputFinHora.setVisible(false);
        radioPerfil.setVisible(false);
        radioAlarma.setVisible(false);
        itemPerfiles.setVisible(false);
        itemInstructor.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jDateChooser1 = new org.netbeans.modules.form.InvalidComponent();
        tipo = new javax.swing.ButtonGroup();
        cargo = new javax.swing.ButtonGroup();
        pordiaperiodo = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        SUPERIOR = new javax.swing.JLabel();
        SUPERIOR1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtInicioHorario = new javax.swing.JLabel();
        txtInicioFecha = new javax.swing.JLabel();
        txtFinFecha = new javax.swing.JLabel();
        txtFinHorario = new javax.swing.JLabel();
        txtId = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        crearHorario = new javax.swing.JLabel();
        inputFinHora = new javax.swing.JTextField();
        inputInicioHora = new javax.swing.JTextField();
        inputFinFecha = new org.netbeans.modules.form.InvalidComponent();
        inputId = new javax.swing.JTextField();
        dia = new javax.swing.JRadioButton();
        periodo = new javax.swing.JRadioButton();
        txtTipoCargo = new javax.swing.JLabel();
        radioPerfil = new javax.swing.JRadioButton();
        radioAlarma = new javax.swing.JRadioButton();
        txtInstructor = new javax.swing.JLabel();
        txtPerfil = new javax.swing.JLabel();
        CrearH = new javax.swing.JButton();
        itemPerfiles = new javax.swing.JComboBox<>();
        itemInstructor = new javax.swing.JComboBox<>();
        inputInicioFecha = new org.netbeans.modules.form.InvalidComponent();

        jLabel7.setText("jLabel7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SUPERIOR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/superior.png"))); // NOI18N
        SUPERIOR.setText("jLabel1");
        jPanel1.add(SUPERIOR, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 500, -1, 40));

        SUPERIOR1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/superior.png"))); // NOI18N
        SUPERIOR1.setText("jLabel1");
        jPanel1.add(SUPERIOR1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("creacion horarios");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 190, 40));

        txtInicioHorario.setText("Inicio de hora:");
        jPanel1.add(txtInicioHorario, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 90, 30));

        txtInicioFecha.setText("Inicio de fecha:");
        jPanel1.add(txtInicioFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 90, -1));

        txtFinFecha.setText("Fin de fecha:");
        jPanel1.add(txtFinFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, -1, -1));

        txtFinHorario.setText("Fin de horario:");
        jPanel1.add(txtFinHorario, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, 90, 30));

        txtId.setText("ID");
        jPanel1.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 40, -1));

        jLabel10.setText("Tipo");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 40, -1));
        jPanel1.add(crearHorario, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 60, 50));

        inputFinHora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputFinHoraActionPerformed(evt);
            }
        });
        jPanel1.add(inputFinHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, 120, -1));
        jPanel1.add(inputInicioHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, 120, -1));
        jPanel1.add(inputFinFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, 120, -1));

        inputId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputIdActionPerformed(evt);
            }
        });
        jPanel1.add(inputId, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, 140, -1));

        pordiaperiodo.add(dia);
        dia.setText("Dia");
        dia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diaActionPerformed(evt);
            }
        });
        jPanel1.add(dia, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, -1, -1));

        pordiaperiodo.add(periodo);
        periodo.setText("Periodo");
        periodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                periodoActionPerformed(evt);
            }
        });
        jPanel1.add(periodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, -1, -1));

        txtTipoCargo.setText("Tipo de cargo");
        jPanel1.add(txtTipoCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, 80, -1));

        cargo.add(radioPerfil);
        radioPerfil.setText("Perfil");
        radioPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioPerfilActionPerformed(evt);
            }
        });
        jPanel1.add(radioPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 330, -1, -1));

        cargo.add(radioAlarma);
        radioAlarma.setText("Alarma");
        jPanel1.add(radioAlarma, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 330, -1, -1));

        txtInstructor.setText("Instructor");
        jPanel1.add(txtInstructor, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 360, 90, -1));

        txtPerfil.setText("Perfil");
        jPanel1.add(txtPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 400, -1, -1));

        CrearH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnhorario.png"))); // NOI18N
        CrearH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearHActionPerformed(evt);
            }
        });
        jPanel1.add(CrearH, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 460, 170, 30));

        itemPerfiles.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(itemPerfiles, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 400, 140, -1));

        itemInstructor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(itemInstructor, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 360, 140, -1));
        jPanel1.add(inputInicioFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 120, -1));
        inputInicioFecha.getAccessibleContext().setAccessibleParent(inputInicioFecha);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputFinHoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputFinHoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputFinHoraActionPerformed

    private void periodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_periodoActionPerformed
  boolean p= periodo.isSelected();
  
  if(p==true){
       txtInicioFecha.setText("Inicio Fecha");
       inputInicioFecha.setVisible(true);
       
       txtFinFecha.setText("Fin Fecha");
       inputFinFecha.setVisible(true);
       
       txtInicioHorario.setText("Inicio Horario");
       inputInicioHora.setVisible(true);
       
       txtFinHorario.setText("Fin Horario");
       inputFinHora.setVisible(true);
       
       txtTipoCargo.setText("Cargo");
        radioPerfil.setVisible(true);
        radioAlarma.setVisible(true);
       
       txtInstructor.setText("Instructor");
       itemPerfiles.setVisible(true);
       itemInstructor.setVisible(true);
        }
  
    }//GEN-LAST:event_periodoActionPerformed

    private void radioPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioPerfilActionPerformed
        
    }//GEN-LAST:event_radioPerfilActionPerformed

    private void CrearHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearHActionPerformed
    
        int identificacion = Integer.parseInt(inputId.getText());
      
        String InicioHora =  (inputInicioHora.getText());
        String finHora =  (inputFinHora.getText());
        int instru = itemInstructor.getSelectedIndex();
        int pfiles = itemPerfiles.getSelectedIndex();
        tipo.add(dia);
        tipo.add(periodo);
        cargo.add(radioPerfil);
        cargo.add(radioAlarma);
        
        
    }//GEN-LAST:event_CrearHActionPerformed

    private void inputIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputIdActionPerformed
        
    }//GEN-LAST:event_inputIdActionPerformed

    private void diaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diaActionPerformed
       
        boolean d= dia.isSelected();
        
        if(d==true){
       txtInicioFecha.setText("Fecha");
       inputInicioFecha.setVisible(true);
       
       txtFinFecha.setText("");
       inputFinFecha.setVisible(false);
       
       txtInicioHorario.setText("Inicio Horario");
       inputInicioHora.setVisible(true);
       
       txtFinHorario.setText("Fin Horario");
       inputFinHora.setVisible(true);
       
       txtTipoCargo.setText("Cargo");
        radioPerfil.setVisible(true);
        radioAlarma.setVisible(true);
       
       txtInstructor.setText("Instructor");
       itemPerfiles.setVisible(true);
       itemInstructor.setVisible(true);
        }
        
    }//GEN-LAST:event_diaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearHorarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearHorarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearHorarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearHorarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearHorarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CrearH;
    private javax.swing.JLabel SUPERIOR;
    private javax.swing.JLabel SUPERIOR1;
    private javax.swing.ButtonGroup cargo;
    private javax.swing.JLabel crearHorario;
    private javax.swing.JRadioButton dia;
    private org.netbeans.modules.form.InvalidComponent inputFinFecha;
    private javax.swing.JTextField inputFinHora;
    private javax.swing.JTextField inputId;
    private org.netbeans.modules.form.InvalidComponent inputInicioFecha;
    private javax.swing.JTextField inputInicioHora;
    private javax.swing.JComboBox<String> itemInstructor;
    private javax.swing.JComboBox<String> itemPerfiles;
    private org.netbeans.modules.form.InvalidComponent jDateChooser1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton periodo;
    private javax.swing.ButtonGroup pordiaperiodo;
    private javax.swing.JRadioButton radioAlarma;
    private javax.swing.JRadioButton radioPerfil;
    private javax.swing.ButtonGroup tipo;
    private javax.swing.JLabel txtFinFecha;
    private javax.swing.JLabel txtFinHorario;
    private javax.swing.JLabel txtId;
    private javax.swing.JLabel txtInicioFecha;
    private javax.swing.JLabel txtInicioHorario;
    private javax.swing.JLabel txtInstructor;
    private javax.swing.JLabel txtPerfil;
    private javax.swing.JLabel txtTipoCargo;
    // End of variables declaration//GEN-END:variables

    
}
